version: "3"
services:
  nginx:
    container_name: dcnmp_nginx
    build:
      context: nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        ALPINE_REPOSITORIES_REPLACE: ${ALPINE_REPOSITORIES_REPLACE}
        TZ: ${TZ}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${CODE_PATH}:/app/www/:rw
      - ${CONF_PATH}/nginx/conf/conf.d:/etc/nginx/conf.d:rw
      - ${CONF_PATH}/nginx/conf/vhost:/etc/nginx/vhost:rw
      - ${CONF_PATH}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${LOG_PATH}/nginx:/var/log/nginx/:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - dcnmp

  php:
    container_name: dcnmp_php
    build:
      context: php
      args:
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        ALPINE_REPOSITORIES_REPLACE: ${ALPINE_REPOSITORIES_REPLACE}
        DEBIAN_REPOSITORIES_REPLACE: ${DEBIAN_REPOSITORIES_REPLACE}
        PHP_VERSION: ${PHP_VERSION}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        PHP_MORE_EXTENSION_INSTALLER: ${PHP_MORE_EXTENSION_INSTALLER}
        PHP_REPLACE_SOURCE: ${PHP_REPLACE_SOURCE}
        PHP_INSTALL_SUPERVISOR: ${PHP_INSTALL_SUPERVISOR}
        PHP_INSTALL_EXTENSION_SCRIPT: ${PHP_INSTALL_EXTENSION_SCRIPT}
        PHP_SWOOLE_VERSION: ${PHP_SWOOLE_VERSION}
        TZ: ${TZ}
    ports:
      - "${PHP_HOST_PORT_9000}:9000"
      - "${PHP_HOST_PORT_9501}:9501"
      - "${PHP_HOST_PORT_9502}:9502"
      - "${PHP_HOST_PORT_18306}:18306"
    volumes:
      - ${CODE_PATH}:/app/www/:rw
      - ${CONF_PATH}/php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ${CONF_PATH}/php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${CONF_PATH}/php/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:rw
      - ${CONF_PATH}/php/conf/supervisor:/etc/supervisor:rw
      - ${LOG_PATH}/${PHP_VERSION}:/var/log/php:rw
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    networks:
      - dcnmp

  mysql:
    container_name: dcnmp_mysql
    build:
      context: mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${CONF_PATH}/mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
      - ${DATA_PATH}/mysql:/var/lib/mysql:rw
      - ${LOG_PATH}/mysql:/var/log/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "${TZ}"
    networks:
      - dcnmp

  mongodb:
    container_name: dcnmp_mongodb
    build:
      context: mongodb
      args:
        MONGODB_VERSION: ${MONGODB_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
      TZ: "${TZ}"
    volumes:
      - ${DATA_PATH}/mongodb:/data/db:rw
      - ${DATA_PATH}/mongodb/mongo_key:/mongo:rw
      - ${LOG_PATH}/mongodb:/var/log/mongodb/:rw
    ports:
      - "${MONGODB_HOST_PORT}:27017"
    restart: always
    stdin_open: true
    tty: true
    networks:
      - dcnmp
    command:
      --auth

  redis:
    container_name: dcnmp_redis
    build:
      context: redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        ALPINE_REPOSITORIES_REPLACE: ${ALPINE_REPOSITORIES_REPLACE}
        TZ: ${TZ}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${CONF_PATH}/redis/conf/redis.conf:/etc/redis.conf:rw
      - ${DATA_PATH}/redis:/data:rw
    restart: always
    stdin_open: true
    tty: true
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - dcnmp

  rabbitmq:
    container_name: dcnmp_rabbitmq
    build:
      context: rabbitmq
      args:
        RABBITMQ_VERSION: ${RABBITMQ_VERSION}
    ports:
      - "${RABBITMQ_HOST_PORT_C}:5672"
      - "${RABBITMQ_HOST_PORT_S}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      TZ: "${TZ}"
    volumes:
      - ${LOG_PATH}/rabbitmq:/var/log/rabbitmq:rw
      - ${DATA_PATH}/rabbitmq:/var/lib/rabbitmq:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - dcnmp

networks:
  dcnmp:
