version: "3"
services:
  nginx:
    container_name: dcnmp_nginx
    build:
      context: nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        ALPINE_REPOSITORIES_REPLACE: ${ALPINE_REPOSITORIES_REPLACE}
        TZ: ${TZ}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${CODE_PATH}:/app/www/:rw
      - ${CONF_PATH}/nginx/conf/conf.d:/etc/nginx/conf.d:rw
      - ${CONF_PATH}/nginx/conf/vhost:/etc/nginx/vhost:rw
      - ${CONF_PATH}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${LOG_PATH}/nginx:/var/log/nginx/:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - dcnmp

  vaultwarden:
    container_name: dcnmp_vaultwarden
    build:
      context: vaultwarden
      args:
        - VAULTWARDEN_VERSION=${VAULTWARDEN_VERSION}
    environment:
      - LOG_FILE=/var/log/bitwarden.log
    ports:
      - "${VAULTWARDEN_HTTP_PORT}:80"
      - "${VAULTWARDEN_HTTP_PORT_3012}:3012"
    restart: always
    volumes:
      - ${DATA_PATH}/vaultwarden:/data
      - ${LOG_PATH}/vaultwarden/bitwarden.log:/var/log/bitwarden.log
    networks:
      - dcnmp

networks:
  dcnmp:

